before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tidy
language: python
cache: pip
python:
  - "3.6"
  - "3.6-dev"
script:
  - pycodestyle
  - pydocstyle
  - pylint *.py
  - tidy -version
  - tidy -config .tidyrc -errors docs/*.html
  - piprot
