before_install:
  - wget https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-64bit.deb
  - sudo apt-get -y autoremove tidy-lib
  - sudo dpkg -i tidy-5.4.0-64bit.deb
language: python
cache: pip
python:
  - "3.6"
  - "3.6-dev"
script:
  - pycodestyle
  - pydocstyle
  - pylint *.py
  - tidy -config .tidyrc -errors docs/*.html
  - piprot
