---
title: Craig Anderson
description:
    Personal site of Craig Anderson, a freelance web developer specialising in Python and Django based in London, England.
    Fan of punk rock and craft beer.
    Not a sportsperson or an actor.
email: craiga@craiga.id.au
url: https://www.craiga.id.au
lang: en_AU
gravatar_hash: b593bb966ccde8a4a4fbdc32d2aafb6f
logo: https://gravatar.com/avatar/b593bb966ccde8a4a4fbdc32d2aafb6f.jpeg?size=400

author:
  name: Craig Anderson
  twitter: _craiga

twitter:
  username: _craiga

facebook:
  publisher: https://facebook.com/craiga

seo:
  type: Person
  name: Craig Anderson

collections:
  talks:
    output: true
    permalink: /:collection/:name

social:
  name: Craig Anderson
  links:
    - https://www.linkedin.com/in/craigeanderson
    - https://github.com/craiga
    - https://facebook.com/craiga
    - https://www.instagram.com/_craiga/
    - https://twitter.com/_craiga
    - https://www.last.fm/user/craiganderson
    - https://itunes.apple.com/profile/craigeanderson
    - https://bandcamp.com/craiga
    - https://soundcloud.com/craiga
    - https://www.discogs.com/user/craiga
    - https://www.songkick.com/users/craigeanderson
    - https://untappd.com/user/craiganderson
    - https://distiller.com/profile/craiga
    - https://www.nextfree.co.uk/for/craig-anderson
    - https://uk.yunojuno.com/p/craiga
    - https://bitbucket.org/craiganderson/
    - https://stackoverflow.com/users/1852024/craig-anderson
    - http://amzn.eu/5UobAlG
    - https://www.goodreads.com/craiga
    - https://www.meetup.com/members/24626782/
    - https://www.pinterest.co.uk/craiga/
    - https://www.reddit.com/user/craiga/
    - http://steamcommunity.com/id/craiga
    - http://blog.craiga.id.au/
    - https://www.strava.com/athletes/craiganderson
    - https://www.kiva.org/lender/craiga
    - https://hub.docker.com/u/craiga/
    - https://vimeo.com/craiga
    - https://keybase.io/craiganderson
    - https://www.quora.com/profile/Craig-Anderson-2
    - https://www.gog.com/u/craigeanderson
    - https://angel.co/craiganderson
    - https://www.twitch.tv/craigea

sidebar_links:
  - url: /
    text: Home
    fontawesome-classes: fas fa-home
  - url: /cv
    text: CV
    fontawesome-classes: fas fa-briefcase
  - url: /blog
    text: Blog
    fontawesome-classes: fas fa-blog
  - url: https://www.linkedin.com/in/craigeanderson
    text: LinkedIn
    fontawesome-classes: fab fa-linkedin
  - url: https://github.com/craiga
    text: GitHub
    fontawesome-classes: fab fa-github
  - url: https://facebook.com/craiga
    text: Facebook
    fontawesome-classes: fab fa-facebook
  - url: https://twitter.com/_craiga
    text: Twitter
    fontawesome-classes: fab fa-twitter
  - url: mailto:craiga@craiga.id.au
    text: Email
    fontawesome-classes: fas fa-envelope
  - url: /elsewhere
    text: Elsewhere
    fontawesome-classes: fas fa-globe

external_profiles:
  - url: https://www.linkedin.com/in/craigeanderson
    text: LinkedIn
    fontawesome-classes: fab fa-linkedin
  - url: https://github.com/craiga
    text: GitHub
    fontawesome-classes: fab fa-github
  - url: https://facebook.com/craiga
    text: Facebook
    fontawesome-classes: fab fa-facebook
  - url: https://www.instagram.com/_craiga/
    text: Instagram
    fontawesome-classes: fab fa-instagram
  - url: https://twitter.com/_craiga
    text: Twitter
    fontawesome-classes: fab fa-twitter
  - url: https://www.last.fm/user/craiganderson
    text: Last.fm
    fontawesome-classes: fab fa-lastfm
  - url: https://itunes.apple.com/profile/craigeanderson
    text: Apple Music
    fontawesome-classes: fab fa-apple
  - url: https://bandcamp.com/craiga
    text: Bandcamp
    fontawesome-classes: fab fa-bandcamp
  - url: https://soundcloud.com/craiga
    text: SoundCloud
    fontawesome-classes: fab fa-soundcloud
  - url: https://www.discogs.com/user/craiga
    text: Discogs
    fontawesome-classes: fas fa-compact-disc
  - url: https://www.songkick.com/users/craigeanderson
    text: Songkick
    fontawesome-classes: fas fa-volume-up
  - url: https://untappd.com/user/craiganderson
    text: Untappd
    fontawesome-classes: fab fa-untappd
  - url: https://distiller.com/profile/craiga
    text: Distiller
    fontawesome-classes: fas fa-wine-glass-alt
  - url: https://www.nextfree.co.uk/for/craig-anderson
    text: Nextfree
    fontawesome-classes: fas fa-calendar
  - url: https://uk.yunojuno.com/p/craiga
    text: YunoJuno
    fontawesome-classes: fas fa-asterisk
  - url: https://angel.co/craiganderson
    text: AngelList
    fontawesome-classes: fab fa-angellist
  - url: https://use.worksome.co.uk/profile/28594
    text: Worksome
    fontawesome-classes: fas fa-briefcase
  - url: https://djangogigs.com/developers/craig-anderson2/
    text: Djangogigs
    fontawesome-classes: fas fa-handshake
  - url: https://snap.hr/u/33ba0389-fdfb-4fca-8f37-6ac81bc7630a/
    text: Snap.hr
    fontawesome-classes: fas fa-briefcase
  - url: https://bitbucket.org/craiganderson/
    text: Bitbucket
    fontawesome-classes: fab fa-bitbucket
  - url: https://stackoverflow.com/users/1852024/craig-anderson
    text: Stack Overflow
    fontawesome-classes: fab fa-stack-overflow
  - url: https://pypi.org/user/craiga/
    text: PyPI
    fontawesome-classes: fab fa-python
  - url: http://amzn.eu/5UobAlG
    text: Amazon
    fontawesome-classes: fab fa-amazon
  - url: https://www.goodreads.com/craiga
    text: Goodreads
    fontawesome-classes: fab fa-goodreads
  - url: https://www.meetup.com/members/24626782/
    text: Meetup
    fontawesome-classes: fab fa-meetup
  - url: https://www.pinterest.co.uk/craiga/
    text: Pinterest
    fontawesome-classes: fab fa-pinterest
  - url: https://www.reddit.com/user/craiga/
    text: Reddit
    fontawesome-classes: fab fa-reddit
  - url: https://www.producthunt.com/@craiga
    text: Product Hunt
    fontawesome-classes: fab fa-product-hunt
  - url: http://steamcommunity.com/id/craiga
    text: Steam
    fontawesome-classes: fab fa-steam
  - text: SW-0552-7913-6509
    fontawesome-classes: fab fa-nintendo-switch
  - url: https://account.xbox.com/en-us/profile?gamertag=craigea
    text: Xbox
    fontawesome-classes: fab fa-xbox
  - url: https://www.gog.com/u/craigeanderson
    text: GOG
    fontawesome-classes: fas fa-gamepad
  - url: https://vgcollect.com/craiga
    text: VGCollect
    fontawesome-classes: fas fa-gamepad
  - url: https://www.twitch.tv/craigea
    text: Twitch
    fontawesome-classes: fab fa-twitch
  - url: http://blog.craiga.id.au/
    text: Tumblr
    fontawesome-classes: fab fa-tumblr
  - url: https://curiouscat.me/craiga
    text: Curious Cat
    fontawesome-classes: fas fa-cat
  - url: https://www.strava.com/athletes/craiganderson
    text: Strava
    fontawesome-classes: fab fa-strava
  - url: https://www.kiva.org/lender/craiga
    text: Kiva
    fontawesome-classes: fas fa-leaf
  - url: https://hub.docker.com/u/craiga/
    text: Docker Hub
    fontawesome-classes: fab fa-docker
  - url: https://vimeo.com/craiga
    text: Vimeo
    fontawesome-classes: fab fa-vimeo
  - url: https://keybase.io/craiganderson
    text: Keybase
    fontawesome-classes: fab fa-keybase
  - url: https://www.quora.com/profile/Craig-Anderson-2
    text: Quora
    fontawesome-classes: fab fa-quora
  - url: https://trello.com/craigea
    text: Trello
    fontawesome-classes: fab fa-trello
  - url: https://www.patreon.com/craiga
    text: Patreon
    fontawesome-classes: fab fa-patreon

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: '**/plugin/**'
    values:
      sitemap: false

permalink: /:categories/:year/:month/:day/:title
